-- https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages

local options = {
      ensure_installed = {
        "bash",
        "comment",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "hcl",
        "html",
        "ini",
        "javascript",
        "json",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown",
        "markdown_inline",
        "mermaid",
        "python",
        "query",
        "requirements",
        "rst",
        "sql",
        "terraform",
        "toml",
        "tsv",
        "xml",
        "yaml",
      },
}

return options
